<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fi" sourcelanguage="en">
    <context>
        <name>@default</name>
        <message>
            <location filename="../test/test_translations.py" line="48"/>
            <source>Good morning</source>
            <translation>Hyvää huomenta</translation>
        </message>
        <message>
            <location filename="../qaava.py" line="169"/>
            <source>&amp;Qaava</source>
            <translation>&amp;Qaava</translation>
        </message>
        <message>
            <location filename="../qaava.py" line="131"/>
            <source>Qaava</source>
            <translation>Qaava</translation>
        </message>
        <message>
            <location filename="../qaava.py" line="139"/>
            <source>Initialize database</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="35"/>
            <source>Auth config error occurred while fetching database connection parameters:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="39"/>
            <source>Error occurred while fetching database connection parameters:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="51"/>
            <source>Canceling</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="51"/>
            <source>Could not continue initializing without username and password</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="58"/>
            <source>Database connection error</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="58"/>
            <source>Could not access the database.</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="64"/>
            <source>Network error:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="64"/>
            <source>Could not load schema for the plan. Check your internet connection. Details:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="69"/>
            <source>Not implemented:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="69"/>
            <source>Schema for the selected plan is not implemented yet</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="77"/>
            <source>Connection error:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="77"/>
            <source>Could not connect to the database:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="80"/>
            <source>Error occurred while injecting schema:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="82"/>
            <source>Success</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/db_initializer.py" line="82"/>
            <source>Database initialized succesfully with land use plan</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_initializer_dialog.py" line="31"/>
            <source>Run</source>
            <translation type="unfinished"></translation>
        </message>
    </context>
    <context>
        <name>AskCredentials</name>
        <message>
            <location filename="../database_tools/gui/db_tools_ask_credentials_dialog.ui" line="14"/>
            <source>Dialog</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_ask_credentials_dialog.ui" line="20"/>
            <source>Username or password for the database connection were not saved by QGIS. If you have no password,
                just leave the field empty
            </source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_ask_credentials_dialog.ui" line="35"/>
            <source>Username:</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_ask_credentials_dialog.ui" line="42"/>
            <source>Password:</source>
            <translation type="unfinished"></translation>
        </message>
    </context>
    <context>
        <name>InitializeDatabase</name>
        <message>
            <location filename="../database_tools/gui/db_tools_initializer_dialog.ui" line="14"/>
            <source>Dialog</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_initializer_dialog.ui" line="22"/>
            <source>Database initialization</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_initializer_dialog.ui" line="28"/>
            <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;This utility will turn PostgreSQL/PostGIS database
                into a Qaava land use planning database. &lt;/p&gt;&lt;p&gt;At the moment there are 2 possible database
                models to choose from: &lt;a href=&quot;https://github.com/GispoCoding/qaava/tree/master/asemakaavan-tietomalli&quot;&gt;&lt;span
                style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;a detailed land use plan database model&lt;/span&gt;&lt;/a&gt;
                and a general plan database model.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;
            </source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_initializer_dialog.ui" line="43"/>
            <source>Available PostGIS databases</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_initializer_dialog.ui" line="57"/>
            <source>Data Model for the database</source>
            <translation type="unfinished"></translation>
        </message>
        <message>
            <location filename="../database_tools/gui/db_tools_initializer_dialog.ui" line="84"/>
            <source>I understand that this action might erase all content in the database</source>
            <translation type="unfinished"></translation>
        </message>
    </context>
</TS>
